name: autosms_client
description: AutoSMS.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cookie_jar: ^4.0.2
  dio: ^5.1.2
  dio_cookie_manager: ^3.0.0
  dynamic_color: ^1.6.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.5
  google_fonts: ^4.0.4
  json_serializable: ^6.7.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/logo.png
    - assets/logo_200.png
    - assets/logo_150.png
    - assets/logo_100.png
    - assets/fondo.jpg
    - assets/fondo_2.jpg
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: false
  macos:
    generate: false
  windows:
    generate: false
  linux:
    generate: false